/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Classroom(props) {
  const { nodes, materials } = useGLTF("models/env.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-3.139, -0.074, 3.247]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood.geometry}
          material={materials.Atlas}
          scale={100}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Message_Board.geometry}
        material={materials.Mat}
        position={[0.195, 0.278, -3.989]}
        rotation={[0, -1.571, 0]}
        scale={0.035}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group427675855001.geometry}
        material={materials["mat19.001"]}
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1606767967001.geometry}
        material={materials["mat20.001"]}
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1246942833001.geometry}
        material={materials["mat20.001"]}
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <group
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1103958513001.geometry}
          material={materials["mat18.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1103958513001_1.geometry}
          material={materials["mat19.001"]}
        />
      </group>
      <group
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh205479027001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh205479027001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group970697144001.geometry}
        material={materials["mat17.001"]}
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group848587833001.geometry}
        material={materials["mat17.001"]}
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1840719534001.geometry}
        material={materials["mat17.001"]}
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1477700025001.geometry}
        material={materials["mat19.001"]}
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <group
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1774544435001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1774544435001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1856349250001.geometry}
        material={materials["mat19.001"]}
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group298871933001.geometry}
        material={materials["mat17.001"]}
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1512631129001.geometry}
        material={materials["mat17.001"]}
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <group
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh2011576104001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh2011576104001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <group
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1024187379001.geometry}
          material={materials["mat18.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1024187379001_1.geometry}
          material={materials["mat19.001"]}
        />
      </group>
      <group
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1785529362001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1785529362001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <group
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh451389640001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh451389640001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <group
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh928384235001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh928384235001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <group
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh765891613001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh765891613001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <group
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh491062930001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh491062930001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <group
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh830606209001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh830606209001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <group
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh11767427001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh11767427001_1.geometry}
          material={materials["mat18.001"]}
        />
      </group>
      <group
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1614564418001.geometry}
          material={materials["mat18.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1614564418001_1.geometry}
          material={materials["mat19.001"]}
        />
      </group>
      <group
        position={[4.211, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh77709967001.geometry}
          material={materials["mat19.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh77709967001_1.geometry}
          material={materials["mat18.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh77709967001_2.geometry}
          material={materials["mat17.001"]}
        />
      </group>
      <group
        position={[-0.277, -0.025, -5.307]}
        rotation={[Math.PI, -0.602, Math.PI]}
      >
        <group
          position={[-0.536, 1.037, -4.292]}
          rotation={[-Math.PI / 2, 0, 1.37]}
          scale={48.098}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Blank_Picture_Frame|Node007|Dupli|_1"].geometry}
            material={materials["mat21.009"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Blank_Picture_Frame|Node007|Dupli|_2"].geometry}
            material={materials["mat22.006"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Blank_Picture_Frame|Node007|Dupli|_3"].geometry}
            material={materials["mat15.007"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Blank_Picture_Frame|Node007|Dupli|_4"].geometry}
            material={materials["mat24.003"]}
          />
        </group>
        <group
          position={[-0.897, 0.308, -3.493]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={212.203}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cabinet_Bed_Drawer_Tabl_1.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cabinet_Bed_Drawer_Tabl_2.geometry}
            material={materials._defaultMat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cabinet_Bed_Drawer_Tabl_3.geometry}
            material={materials.metal}
          />
        </group>
        <group
          position={[-1.454, 0.633, -4.92]}
          rotation={[-Math.PI / 2, 0, 1.643]}
          scale={2.911}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chair003_1.geometry}
            material={materials["Executive.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chair003_2.geometry}
            material={materials["Executive__1.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chair003_3.geometry}
            material={materials["Executive__2.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chair003_4.geometry}
            material={materials["Executive__3.003"]}
          />
        </group>
        <group
          position={[-1.037, 0.957, -2.813]}
          rotation={[Math.PI, 0, 0]}
          scale={[9999.999, 10000, 9999.999]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Houseplant-bfLOqIV5uP_1"].geometry}
            material={materials["Black.081"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Houseplant-bfLOqIV5uP_2"].geometry}
            material={materials["Brown.033"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Houseplant-bfLOqIV5uP_3"].geometry}
            material={materials["Plant_Green.033"]}
          />
        </group>
        <group
          position={[-1.036, 0.921, -4.943]}
          rotation={[-Math.PI / 2, 0, -1.61]}
          scale={20.517}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1030983910|Dupli|22"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1075691498|Dupli|58"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1149852049|Dupli|53"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1152190519|Dupli|19"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1180881246|Dupli|50"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1238060299|Dupli|28"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1238428394|Dupli|61"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1272091893|Dupli|35"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1316349499|Dupli|39"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1323238240|Dupli|32"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group145618305|Dupli|23"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1486350934|Dupli|63"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group150579309|Dupli|11"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1529968652|Dupli|6"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1571332333|Dupli|33"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1581414308|Dupli|8"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1589752359|Dupli|26"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1629393722|Dupli|64"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1629609685|Dupli|21"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1675960081|Dupli|12"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1740918352|Dupli|46"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1753917514|Dupli|5"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1754683637|Dupli|40"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1764140354|Dupli|60"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1870575723|Dupli|65"].geometry}
            material={materials["mat16.006"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1899843208|Dupli|36"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1956214489|Dupli|14"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group196400395|Dupli|15"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group1976194690|Dupli|18"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group205302596|Dupli|31"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group2074153597|Dupli|20"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group2085389804|Dupli|57"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group2091112366|Dupli|59"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group2106755496|Dupli|4"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group2146178072|Dupli|38"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group252681800|Dupli|7"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group268332703|Dupli|44"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group287159489|Dupli|13"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group295085766|Dupli|9"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group311988427|Dupli|1"].geometry}
            material={materials["mat22.011"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group34220672|Dupli|34"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group384612072|Dupli|10"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group418912012|Dupli|30"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group42243725|Dupli|37"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group425587018|Dupli|"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group449779970|Dupli|3"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group45382983|Dupli|52"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group475225180|Dupli|41"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group573547017|Dupli|49"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group588539140|Dupli|47"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group601803475|Dupli|25"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group616518658|Dupli|56"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group687259746|Dupli|51"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group706802639|Dupli|17"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group729811280|Dupli|48"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group77921105|Dupli|42"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group790925258|Dupli|54"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group801095923|Dupli|29"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group806343109|Dupli|27"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group826580911|Dupli|24"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group873458270|Dupli|55"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group873558583|Dupli|62"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group877249531|Dupli|66"].geometry}
            material={materials["mat9.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group954813675|Dupli|16"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group96314515|Dupli|2"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group96968687|Dupli|43"].geometry}
            material={materials["mat21.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Keyboard001|group993315105|Dupli|45"].geometry}
            material={materials["mat21.013"]}
          />
        </group>
        <group
          position={[-0.564, 1.162, -5.526]}
          rotation={[-Math.PI / 2, 0, 2.301]}
          scale={[8561.474, 8561.474, 8561.471]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Light_Desk001_1.geometry}
            material={materials["Black.097"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Light_Desk001_2.geometry}
            material={materials["LightMetal.027"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Light_Desk001_3.geometry}
            material={materials["White.053"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mouse.geometry}
          material={materials["Material.004"]}
          position={[-1.038, 0.913, -4.453]}
          rotation={[-Math.PI / 2, 0, -1.417]}
          scale={[14736.425, 14736.425, 14736.426]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mousepad.geometry}
          material={materials.Mousepad}
          position={[-1.026, 0.915, -4.458]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[17.231, 20.977, 0.228]}
        />
        <group
          position={[-0.801, 0.614, -4.913]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={3.21}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Node003_1.geometry}
            material={materials._5_Drawer}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Node003_2.geometry}
            material={materials._5_Drawer_1}
          />
        </group>
        <group
          position={[-1.015, 0.946, -5.544]}
          rotation={[-Math.PI / 2, 0, 0.024]}
          scale={219.88}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper_1.geometry}
            material={materials["mat21.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper_2.geometry}
            material={materials["mat15.001"]}
          />
        </group>
        <group
          position={[-0.721, 0.921, -5.252]}
          rotation={[Math.PI / 2, 0, 1.096]}
          scale={5618.099}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Phone_1.geometry}
            material={materials["White.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Phone_2.geometry}
            material={materials["Grey.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Phone_3.geometry}
            material={materials["Black.003"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cup001|Cup|Dupli|"].geometry}
          material={materials["Mat.006"]}
          position={[-0.8, 0.909, -4.316]}
          rotation={[-Math.PI / 2, 0, -0.522]}
          scale={0.219}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Monitor001|iMac|Dupli|"].geometry}
          material={materials["Mat.008"]}
          position={[-0.546, 0.913, -4.926]}
          rotation={[-Math.PI / 2, 0, 3.105]}
          scale={1.135}
        />
      </group>
      <group
        position={[-2.827, 0.455, -3.707]}
        rotation={[Math.PI, -0.013, Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh187267960.geometry}
          material={materials["mat20.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh187267960_1.geometry}
          material={materials["mat17.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh187267960_2.geometry}
          material={materials.mat5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh187267960_3.geometry}
          material={materials.mat21}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh187267960_4.geometry}
          material={materials.mat11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh187267960_5.geometry}
          material={materials.mat9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh187267960_6.geometry}
          material={materials.mat4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh187267960_7.geometry}
          material={materials.mat8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh187267960_8.geometry}
          material={materials.mat13}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh187267960_9.geometry}
          material={materials.mat3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh187267960_10.geometry}
          material={materials.mat7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh187267960_11.geometry}
          material={materials.mat6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh187267960_12.geometry}
          material={materials.mat23}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh187267960_13.geometry}
          material={materials.mat22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh187267960_14.geometry}
          material={materials["mat18.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh187267960_15.geometry}
          material={materials["mat19.003"]}
        />
      </group>
      <group
        position={[3.213, 1.651, -4.142]}
        rotation={[Math.PI, -1.568, Math.PI]}
        scale={0.12}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Wall_Painting_01_Plane002-Mesh"].geometry}
          material={materials["795548"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Wall_Painting_01_Plane002-Mesh_1"].geometry}
          material={materials["039BE5"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Wall_Painting_01_Plane002-Mesh_2"].geometry}
          material={materials.FFFFFF}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Wall_Painting_01_Plane002-Mesh_3"].geometry}
          material={materials["455A64"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Wall_Painting_01_Plane002-Mesh_4"].geometry}
          material={materials.FFEB3B}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Wall_Painting_01_Plane002-Mesh_5"].geometry}
          material={materials.FF9800}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.001"]}
        position={[-2.417, 1.113, 2.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials["Material.001"]}
        position={[-2.417, 0.985, 2.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.001"]}
        position={[-1.912, 1.089, 2.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials["Material.001"]}
        position={[-2.417, 0.174, 1.821]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials["Material.001"]}
        position={[-2.921, 0.174, 2.203]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials["Material.001"]}
        position={[-2.921, 1.063, 2.174]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials["Material.001"]}
        position={[-2.417, 0.867, 1.82]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials["Material.001"]}
        position={[-1.912, 1.089, 2.374]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials["Material.001"]}
        position={[-2.417, 1.17, 3.143]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials["Material.001"]}
        position={[-2.418, 0.572, 2.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials["Material.001"]}
        position={[-2.116, 1.142, 3.277]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials["Material.001"]}
        position={[-2.105, 0.582, 2.699]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={materials["Material.001"]}
        position={[-2.19, 1.066, 3.282]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials["Material.001"]}
        position={[-2.417, 1.113, 2.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials["Material.001"]}
        position={[-2.417, 0.985, 2.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={materials["Material.001"]}
        position={[-1.912, 1.089, 2.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={materials["Material.001"]}
        position={[-2.417, 0.174, 1.821]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials["Material.001"]}
        position={[-2.921, 0.174, 2.203]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials["Material.001"]}
        position={[-2.921, 1.063, 2.174]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012.geometry}
        material={materials["Material.001"]}
        position={[-2.417, 0.867, 1.82]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013.geometry}
        material={materials["Material.001"]}
        position={[-1.912, 1.089, 2.374]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials["Material.001"]}
        position={[-2.417, 1.17, 3.143]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials["Material.001"]}
        position={[-2.418, 0.572, 2.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials["Material.001"]}
        position={[-2.116, 1.142, 3.277]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder014.geometry}
        material={materials["Material.001"]}
        position={[-2.105, 0.582, 2.699]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder015.geometry}
        material={materials["Material.001"]}
        position={[-2.19, 1.066, 3.282]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPipe6.geometry}
        material={materials.lambert1}
        position={[0.036, 0, 0.018]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPipe6001.geometry}
        material={materials["lambert1.001"]}
        position={[2.459, 0, 0.018]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder016.geometry}
        material={materials["Material.002"]}
        position={[0.232, 1.066, 3.282]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder017.geometry}
        material={materials["Material.002"]}
        position={[0.317, 0.582, 2.699]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder018.geometry}
        material={materials["Material.002"]}
        position={[0.51, 1.089, 2.374]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder019.geometry}
        material={materials["Material.002"]}
        position={[0.006, 0.867, 1.82]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder020.geometry}
        material={materials["Material.002"]}
        position={[-0.499, 1.063, 2.174]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder021.geometry}
        material={materials["Material.002"]}
        position={[-0.498, 0.174, 2.203]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder022.geometry}
        material={materials["Material.002"]}
        position={[0.006, 0.174, 1.821]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder023.geometry}
        material={materials["Material.002"]}
        position={[0.51, 1.089, 2.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder024.geometry}
        material={materials["Material.002"]}
        position={[0.232, 1.066, 3.282]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder025.geometry}
        material={materials["Material.002"]}
        position={[0.317, 0.582, 2.699]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder026.geometry}
        material={materials["Material.002"]}
        position={[0.51, 1.089, 2.374]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder027.geometry}
        material={materials["Material.002"]}
        position={[0.006, 0.867, 1.82]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder028.geometry}
        material={materials["Material.002"]}
        position={[-0.499, 1.063, 2.174]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder029.geometry}
        material={materials["Material.002"]}
        position={[-0.498, 0.174, 2.203]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder030.geometry}
        material={materials["Material.002"]}
        position={[0.006, 0.174, 1.821]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder031.geometry}
        material={materials["Material.002"]}
        position={[0.51, 1.089, 2.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials["Material.002"]}
        position={[0.306, 1.142, 3.277]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials["Material.002"]}
        position={[0.005, 0.572, 2.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials["Material.002"]}
        position={[0.006, 1.17, 3.143]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials["Material.002"]}
        position={[0.006, 0.985, 2.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials["Material.002"]}
        position={[0.006, 1.113, 2.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials["Material.002"]}
        position={[0.306, 1.142, 3.277]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials["Material.002"]}
        position={[0.005, 0.572, 2.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials["Material.002"]}
        position={[0.006, 1.17, 3.143]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={materials["Material.002"]}
        position={[0.006, 0.985, 2.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials["Material.002"]}
        position={[0.006, 1.113, 2.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPipe6002.geometry}
        material={materials["lambert1.002"]}
        position={[4.816, 0, 0.018]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder032.geometry}
        material={materials["Material.003"]}
        position={[2.867, 1.089, 2.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder033.geometry}
        material={materials["Material.003"]}
        position={[2.362, 0.174, 1.821]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder034.geometry}
        material={materials["Material.003"]}
        position={[1.858, 0.174, 2.203]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder035.geometry}
        material={materials["Material.003"]}
        position={[1.858, 1.063, 2.174]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder036.geometry}
        material={materials["Material.003"]}
        position={[2.362, 0.867, 1.82]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder037.geometry}
        material={materials["Material.003"]}
        position={[2.867, 1.089, 2.374]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder038.geometry}
        material={materials["Material.003"]}
        position={[2.674, 0.582, 2.699]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder039.geometry}
        material={materials["Material.003"]}
        position={[2.589, 1.066, 3.282]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder040.geometry}
        material={materials["Material.003"]}
        position={[2.867, 1.089, 2.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder041.geometry}
        material={materials["Material.003"]}
        position={[2.362, 0.174, 1.821]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder042.geometry}
        material={materials["Material.003"]}
        position={[1.858, 0.174, 2.203]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder043.geometry}
        material={materials["Material.003"]}
        position={[1.858, 1.063, 2.174]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder044.geometry}
        material={materials["Material.003"]}
        position={[2.362, 0.867, 1.82]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder045.geometry}
        material={materials["Material.003"]}
        position={[2.867, 1.089, 2.374]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder046.geometry}
        material={materials["Material.003"]}
        position={[2.674, 0.582, 2.699]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder047.geometry}
        material={materials["Material.003"]}
        position={[2.589, 1.066, 3.282]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={materials["Material.003"]}
        position={[2.362, 1.113, 2.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={materials["Material.003"]}
        position={[2.362, 0.985, 2.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={materials["Material.003"]}
        position={[2.362, 1.17, 3.143]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={materials["Material.003"]}
        position={[2.361, 0.572, 2.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={materials["Material.003"]}
        position={[2.663, 1.142, 3.277]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={materials["Material.003"]}
        position={[2.362, 1.113, 2.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={materials["Material.003"]}
        position={[2.362, 0.985, 2.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={materials["Material.003"]}
        position={[2.362, 1.17, 3.143]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={materials["Material.003"]}
        position={[2.361, 0.572, 2.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={materials["Material.003"]}
        position={[2.663, 1.142, 3.277]}
      />
      <group position={[-1.788, -0.074, 3.247]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood001.geometry}
          material={materials["Atlas.001"]}
          scale={100}
        />
      </group>
      <group position={[-0.428, -0.074, 3.247]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood002.geometry}
          material={materials["Atlas.002"]}
          scale={100}
        />
      </group>
      <group position={[3.631, -0.074, 3.247]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood003.geometry}
          material={materials["Atlas.003"]}
          scale={100}
        />
      </group>
      <group position={[2.271, -0.074, 3.247]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood004.geometry}
          material={materials["Atlas.004"]}
          scale={100}
        />
      </group>
      <group position={[0.92, -0.074, 3.247]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood005.geometry}
          material={materials["Atlas.005"]}
          scale={100}
        />
      </group>
      <group position={[0.92, -0.074, 1.884]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood006.geometry}
          material={materials["Atlas.006"]}
          scale={100}
        />
      </group>
      <group position={[2.271, -0.074, 1.884]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood007.geometry}
          material={materials["Atlas.007"]}
          scale={100}
        />
      </group>
      <group position={[3.631, -0.074, 1.884]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood008.geometry}
          material={materials["Atlas.008"]}
          scale={100}
        />
      </group>
      <group position={[-0.428, -0.074, 1.884]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood009.geometry}
          material={materials["Atlas.009"]}
          scale={100}
        />
      </group>
      <group position={[-1.788, -0.074, 1.884]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood010.geometry}
          material={materials["Atlas.010"]}
          scale={100}
        />
      </group>
      <group position={[-3.139, -0.074, 1.884]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood011.geometry}
          material={materials["Atlas.011"]}
          scale={100}
        />
      </group>
      <group position={[-3.139, -0.074, -0.834]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood012.geometry}
          material={materials["Atlas.012"]}
          scale={100}
        />
      </group>
      <group position={[-1.788, -0.074, -0.834]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood013.geometry}
          material={materials["Atlas.013"]}
          scale={100}
        />
      </group>
      <group position={[-0.428, -0.074, -0.834]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood014.geometry}
          material={materials["Atlas.014"]}
          scale={100}
        />
      </group>
      <group position={[3.631, -0.074, -0.834]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood015.geometry}
          material={materials["Atlas.015"]}
          scale={100}
        />
      </group>
      <group position={[2.271, -0.074, -0.834]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood016.geometry}
          material={materials["Atlas.016"]}
          scale={100}
        />
      </group>
      <group position={[0.92, -0.074, -0.834]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood017.geometry}
          material={materials["Atlas.017"]}
          scale={100}
        />
      </group>
      <group position={[0.92, -0.074, 0.529]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood018.geometry}
          material={materials["Atlas.018"]}
          scale={100}
        />
      </group>
      <group position={[2.271, -0.074, 0.529]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood019.geometry}
          material={materials["Atlas.019"]}
          scale={100}
        />
      </group>
      <group position={[3.631, -0.074, 0.529]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood020.geometry}
          material={materials["Atlas.020"]}
          scale={100}
        />
      </group>
      <group position={[-0.428, -0.074, 0.529]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood021.geometry}
          material={materials["Atlas.021"]}
          scale={100}
        />
      </group>
      <group position={[-1.788, -0.074, 0.529]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood022.geometry}
          material={materials["Atlas.022"]}
          scale={100}
        />
      </group>
      <group position={[-3.139, -0.074, 0.529]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood023.geometry}
          material={materials["Atlas.023"]}
          scale={100}
        />
      </group>
      <group position={[-3.139, -0.074, -2.175]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood024.geometry}
          material={materials["Atlas.024"]}
          scale={100}
        />
      </group>
      <group position={[-1.788, -0.074, -2.175]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood025.geometry}
          material={materials["Atlas.025"]}
          scale={100}
        />
      </group>
      <group position={[-0.428, -0.074, -2.175]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood026.geometry}
          material={materials["Atlas.026"]}
          scale={100}
        />
      </group>
      <group position={[3.631, -0.074, -2.175]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood027.geometry}
          material={materials["Atlas.027"]}
          scale={100}
        />
      </group>
      <group position={[2.271, -0.074, -2.175]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood028.geometry}
          material={materials["Atlas.028"]}
          scale={100}
        />
      </group>
      <group position={[0.92, -0.074, -2.175]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood029.geometry}
          material={materials["Atlas.029"]}
          scale={100}
        />
      </group>
      <group position={[0.92, -0.074, -3.537]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood030.geometry}
          material={materials["Atlas.030"]}
          scale={100}
        />
      </group>
      <group position={[2.271, -0.074, -3.537]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood031.geometry}
          material={materials["Atlas.031"]}
          scale={100}
        />
      </group>
      <group position={[3.631, -0.074, -3.537]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood032.geometry}
          material={materials["Atlas.032"]}
          scale={100}
        />
      </group>
      <group position={[-0.428, -0.074, -3.537]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood033.geometry}
          material={materials["Atlas.033"]}
          scale={100}
        />
      </group>
      <group position={[-1.788, -0.074, -3.537]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood034.geometry}
          material={materials["Atlas.034"]}
          scale={100}
        />
      </group>
      <group position={[-3.139, -0.074, -3.537]} scale={0.339}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor_Wood035.geometry}
          material={materials["Atlas.035"]}
          scale={100}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube030.geometry}
        material={materials["Material.005"]}
        position={[-3.758, 1.675, 0]}
        scale={[0.046, 1.743, 4.203]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031.geometry}
        material={materials["Material.005"]}
        position={[4.309, 1.675, 0]}
        scale={[0.046, 1.743, 4.203]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube032.geometry}
        material={materials["Material.005"]}
        position={[0.245, 1.675, -4.197]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.046, 1.743, 4.203]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group970697144002.geometry}
        material={materials["mat17.002"]}
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <group
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh928384235002.geometry}
          material={materials["mat19.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh928384235002_1.geometry}
          material={materials["mat18.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group848587833002.geometry}
        material={materials["mat17.002"]}
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <group
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh830606209002.geometry}
          material={materials["mat19.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh830606209002_1.geometry}
          material={materials["mat18.002"]}
        />
      </group>
      <group
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh77709967002.geometry}
          material={materials["mat19.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh77709967002_1.geometry}
          material={materials["mat18.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh77709967002_2.geometry}
          material={materials["mat17.002"]}
        />
      </group>
      <group
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh765891613002.geometry}
          material={materials["mat19.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh765891613002_1.geometry}
          material={materials["mat18.002"]}
        />
      </group>
      <group
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh491062930002.geometry}
          material={materials["mat19.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh491062930002_1.geometry}
          material={materials["mat18.002"]}
        />
      </group>
      <group
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh451389640002.geometry}
          material={materials["mat19.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh451389640002_1.geometry}
          material={materials["mat18.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group427675855002.geometry}
        material={materials["mat19.002"]}
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group298871933002.geometry}
        material={materials["mat17.002"]}
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <group
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh205479027002.geometry}
          material={materials["mat19.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh205479027002_1.geometry}
          material={materials["mat18.002"]}
        />
      </group>
      <group
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh2011576104002.geometry}
          material={materials["mat19.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh2011576104002_1.geometry}
          material={materials["mat18.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1856349250002.geometry}
        material={materials["mat19.002"]}
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1840719534002.geometry}
        material={materials["mat17.002"]}
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <group
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1785529362002.geometry}
          material={materials["mat19.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1785529362002_1.geometry}
          material={materials["mat18.002"]}
        />
      </group>
      <group
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1774544435002.geometry}
          material={materials["mat19.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1774544435002_1.geometry}
          material={materials["mat18.002"]}
        />
      </group>
      <group
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1614564418002.geometry}
          material={materials["mat18.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1614564418002_1.geometry}
          material={materials["mat19.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1606767967002.geometry}
        material={materials["mat20.002"]}
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1512631129002.geometry}
        material={materials["mat17.002"]}
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1477700025002.geometry}
        material={materials["mat19.002"]}
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1246942833002.geometry}
        material={materials["mat20.002"]}
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      />
      <group
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh11767427002.geometry}
          material={materials["mat19.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh11767427002_1.geometry}
          material={materials["mat18.002"]}
        />
      </group>
      <group
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1103958513002.geometry}
          material={materials["mat18.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1103958513002_1.geometry}
          material={materials["mat19.002"]}
        />
      </group>
      <group
        position={[-3.667, 1.483, -0.386]}
        rotation={[0, -1.571, 0]}
        scale={0.722}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1024187379002.geometry}
          material={materials["mat18.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1024187379002_1.geometry}
          material={materials["mat19.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/env.glb");
